#!/usr/bin/env python
import os
import sys

MY_DIR = os.path.dirname(os.path.realpath(__file__))
REPO_DIR = os.path.dirname(MY_DIR)
MODULE_DIR = os.path.join(REPO_DIR, "nopackage")
if not os.path.isfile(os.path.join(MODULE_DIR, "__init__.py")):
    print("Error: '{}' is not a module. This script should be symlinked"
          " and the original should always be in the repo's scripts folder"
          "".format(MODULE_DIR),
          file=sys.stderr)
    import nopackage
    print("The system's nopackage is being used instead.", file=sys.stderr)
else:
    sys.path.insert(0, REPO_DIR)  # Use the directory *containing* the module
    import nopackage

from nopackage import main

if __name__ == "__main__":
    sys.exit(main())
